version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./provision/mysql/init/:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: services
      TZ: UTC
    ports:
      - "3306:3306"
